FROM assembly_v0.0824:latest

# Quast
ENV ReportAll=--report-all-metrics
ENV AddArgs= 

# multiQC
ENV ReportWhat=Lighter
#Trimmomatic or Lighter

COPY ./Scripts/ $PATH_Scripts
RUN ln -sf $PATH_Scripts/*.sh /usr/local/bin/
RUN ln -sf $PATH_Scripts/*.R /usr/local/bin/


USER repl
WORKDIR /home/repl