FROM assembly_v0.0824:latest


RUN apt-get update -y && apt-get install bc && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV tidyup=1
ENV LowStorage=1
# SPADES
ENV spades_polish= 
# to turn on spades polihing used the following argument value: --careful


# Quast
ENV ReportAll=--report-all-metrics
ENV AddArgs= 
ENV Quast_trimmom=0

# multiQC
ENV ReportWhat=Lighter
#Trimmomatic or Lighter

# Samtools
ENV samtools=1

# KAT
ENV crashwait=20

#Trimmomatic
ENV TrimMem=30G

COPY ./Scripts/ $PATH_Scripts
RUN ln -sf $PATH_Scripts/*.sh /usr/local/bin/
RUN ln -sf $PATH_Scripts/*.R /usr/local/bin/


USER repl
WORKDIR /home/repl